version: '3.8'

services:
  pocketbase:
    build: ./pocketbase
    ports:
      - '8080:8080'
    volumes:
      - './pocketbase-data:/pb/pb_data'
  server:
    build: ./server
    ports:
      - '4000:4000'